### ISSUE TITLE
CircleCI Partner Review

### ISSUE THREAD

**Issue by brivu** [shipyardbuild/circleci-orb#3]
Hey @elliott-king!

This is Brian from CircleCI's Community and Partner Engineering Team.  It was really great to meet you today.  I've been taking a look at your orb and it looks really good so far.  I have a couple of suggestions below (most of which we discussed on our call today). 

- Update your description to reflect the value proposition that your orb gives as a whole.  For example: 

> Use Shipyard with CircleCI to ...... 

- You currently have a usage example called "example".  Please rename this usage example to match the use case you're trying to demonstrate.  Here's a snippet from our [Orb Authoring Best Practices](https://circleci.com/docs/2.0/orbs-best-practices/?section=configuration)

> Each included usage example should be named for a specific use-case to instruct the user in how to accomplish a task. Example: `install_cli_and_deploy`, `scan_docker_container`, or `test_application_with_this-tool`

- Please also consider adding more usage examples that reflects some real life use cases.  This helps showcase the value of the orb to potential users.  [The Node Orb](https://circleci.com/developer/orbs/orb/circleci/node) has some great examples that are super practical.  It enables users just copy and paste the example right into their own config files.  

- Please add the env_var_name parameter to your API token for documentation purposes. You can find an example in our [Orb Authoring Best Practices](https://circleci.com/docs/2.0/orbs-best-practices/?section=configuration) under the "Commands" section

Let me know when you've made the changes and I'll be sure to take another look.  

Thanks! 
Brian

**Comment by elliott-king** [comment]
@brivu It looks like [executors are only used for jobs](https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors). Should we remove the sample one from the orb?

**Comment by brivu** [comment]
Hey @elliott-king, 

You're correct on that one.  You should remove the executors from the orb. 

Brian

**Comment by KyleTryon** [comment]
@elliott-king just wanted to reach out for an update and ask how we are looking 👍

**Comment by rogerioshieh** [comment]
Hey @KyleTryon, thanks for reaching out! 

I believe the PR https://github.com/shipyardbuild/circleci-orb/pull/4 should address all comments mentioned on this issue. I pinged @brivu to ensure that we don't have anything else to address, but haven't heard back yet--from my testing everything was working well, but let us know if we missed something and we will fix it on PR https://github.com/shipyardbuild/circleci-orb/pull/4.

Thanks again!

**Comment by elliott-king** [comment]
All set - completed by #4
